test-setup:
	cd tests/test_example_v1 && sui move build --dump-bytecode-as-base64 >> ../../test_example_v1_build_output.json
	cd tests/test_example_v2 && sui move build --dump-bytecode-as-base64 >> ../../test_example_v2_build_output.json 
